language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_script:
  - 'if [ "$TRAVIS_PHP_VERSION" = "5.4" ]; then rm composer.lock; fi'
  - composer install -n --prefer-source

script: "./robo test"
