site_name: Robo
theme: mkdocs
site_favicon: img/favicon.png
theme_dir: robotheme
site_url: http://robo.li
repo_url: https://github.com/codegyre/robo/
pages:
- Introduction: index.md
- Guides:
  - "Getting Started": getting-started.md
  - Collections: collections.md
- Tasks:
  - "Base Tasks": tasks/Base.md
  - "FileSystem Tasks": tasks/FileSystem.md
  - "File Tasks": tasks/File.md
  - "Composer Tasks": tasks/Composer.md
  - "VCS Tasks": tasks/Vcs.md
  - "Development Tasks": tasks/Development.md
  - "Assets Tasks": tasks/Assets.md
  - "SSH, Rsync Tasks": tasks/Remote.md
  - "Testing Tasks": tasks/Testing.md
  - "NPM Tasks": tasks/Npm.md
  - "Bower Tasks": tasks/Bower.md
  - "Gulp Tasks": tasks/Gulp.md
  - "Docker Tasks": tasks/Docker.md
  - "ApiGen Tasks": tasks/ApiGen.md
- Releases: changelog.md
extra_css:
- /css/robo.css