site_name: Robo
theme: mkdocs
site_favicon: img/favicon.png
theme_dir: robotheme
site_url: http://robo.li
repo_url: https://github.com/codegyre/robo/
pages:
- Introduction: index.md
- Guides:
  - "Getting Started": getting-started.md
  - Collections: collecetion.md
- Tasks:
  - "Base Tasks": Base.md
  - "FileSystem Tasks": FileSystem.md
  - "File Tasks": File.md
  - "Composer Tasks": Composer.md
  - "VCS Tasks": Vcs.md
  - "Development Tasks": Development.md
  - "Assets Tasks": Assets.md
  - "Tasks'": Remote.md 'SSH, Rsync
  - "Testing Tasks": Testing.md
  - "NPM Tasks": Npm.md
  - "Bower Tasks": Bower.md
  - "Gulp Tasks": Gulp.md
  - "Docker Tasks": Docker.md
  - "ApiGen Tasks": ApiGen.md
- Releases: changelog.md
extra_css:
- /css/robo.css